export const readers = [
  {
    name: "إبراهيم الأخضر",
    server: "https://server6.mp3quran.net/akdr/",
    readerId: 1,
    mushafId: 1,
  },
  {
    name: "أكرم العلاقمي",
    server: "https://server9.mp3quran.net/akrm/",
    readerId: 10,
    mushafId: 10,
  },
  {
    name: "ماجد العنزي",
    server: "https://server8.mp3quran.net/majd_onazi/",
    readerId: 100,
    mushafId: 100,
  },
  {
    name: "ماهر المعيقلي",
    server: "https://server12.mp3quran.net/maher/",
    readerId: 102,
    mushafId: 102,
  },
  {
    name: "محمد البراك",
    server: "https://server13.mp3quran.net/braak/",
    readerId: 105,
    mushafId: 105,
  },
  {
    name: "محمد الطبلاوي",
    server: "https://server12.mp3quran.net/tblawi/",
    readerId: 106,
    mushafId: 106,
  },
  {
    name: "محمد اللحيدان",
    server: "https://server8.mp3quran.net/lhdan/",
    readerId: 107,
    mushafId: 107,
  },
  {
    name: "محمد المحيسني",
    server: "https://server11.mp3quran.net/mhsny/",
    readerId: 108,
    mushafId: 108,
  },
  {
    name: "محمد أيوب",
    server: "https://server8.mp3quran.net/ayyub/",
    readerId: 109,
    mushafId: 109,
  },
  {
    name: "محمد صالح عالم شاه",
    server: "https://server12.mp3quran.net/shah/",
    readerId: 110,
    mushafId: 110,
  },
  {
    name: "محمد جبريل",
    server: "https://server8.mp3quran.net/jbrl/",
    readerId: 111,
    mushafId: 111,
  },
  {
    name: "محمد صديق المنشاوي",
    server: "https://server10.mp3quran.net/minsh/",
    readerId: 112,
    mushafId: 112,
  },
  {
    name: "محمد عبدالكريم",
    server: "https://server12.mp3quran.net/m_krm/",
    readerId: 115,
    mushafId: 115,
  },
  {
    name: "محمود خليل الحصري",
    server: "https://server13.mp3quran.net/husr/",
    readerId: 118,
    mushafId: 118,
  },
  {
    name: "إدريس أبكر",
    server: "https://server6.mp3quran.net/abkr/",
    readerId: 12,
    mushafId: 12,
  },
  {
    name: "محمود علي البنا",
    server: "https://server8.mp3quran.net/bna/",
    readerId: 121,
    mushafId: 121,
  },
  {
    name: "مشاري العفاسي",
    server: "https://server8.mp3quran.net/afs/",
    readerId: 123,
    mushafId: 123,
  },
  {
    name: "مصطفى إسماعيل",
    server: "https://server8.mp3quran.net/mustafa/",
    readerId: 125,
    mushafId: 125,
  },
  {
    name: "مصطفى اللاهوني",
    server: "https://server6.mp3quran.net/lahoni/",
    readerId: 126,
    mushafId: 126,
  },
  {
    name: "مصطفى رعد العزاوي",
    server: "https://server8.mp3quran.net/ra3ad/",
    readerId: 127,
    mushafId: 127,
  },
  {
    name: "معمر الأندونيسي",
    server: "https://server6.mp3quran.net/muamr/",
    readerId: 128,
    mushafId: 128,
  },
  {
    name: "مفتاح السلطني",
    server:
      "https://server14.mp3quran.net/muftah_sultany/Rewayat-Hafs-A-n-Assem/",
    readerId: 129,
    mushafId: 182,
  },
  {
    name: "الزين محمد أحمد",
    server: "https://server9.mp3quran.net/alzain/",
    readerId: 13,
    mushafId: 13,
  },
  {
    name: "عبدالرحمن السويّد",
    server: "https://server16.mp3quran.net/a_swaiyd/Rewayat-Hafs-A-n-Assem/",
    readerId: 135,
    mushafId: 135,
  },
  {
    name: "عبدالإله بن عون",
    server: "https://server16.mp3quran.net/a_binaoun/Rewayat-Hafs-A-n-Assem/",
    readerId: 136,
    mushafId: 136,
  },
  {
    name: "أحمد طالب بن حميد",
    server: "https://server16.mp3quran.net/a_binhameed/Rewayat-Hafs-A-n-Assem/",
    readerId: 137,
    mushafId: 137,
  },
  {
    name: "ماجد الزامل",
    server: "https://server9.mp3quran.net/zaml/",
    readerId: 139,
    mushafId: 139,
  },
  {
    name: "ماهر شخاشيرو",
    server: "https://server10.mp3quran.net/shaksh/",
    readerId: 149,
    mushafId: 149,
  },
  {
    name: "العشري عمران",
    server: "https://server9.mp3quran.net/omran/",
    readerId: 15,
    mushafId: 15,
  },
  {
    name: "محمد المنشد",
    server: "https://server10.mp3quran.net/monshed/",
    readerId: 150,
    mushafId: 150,
  },
  {
    name: "ياسر سلامة",
    server: "https://server12.mp3quran.net/salamah/Rewayat-Hafs-A-n-Assem/",
    readerId: 152,
    mushafId: 152,
  },
  {
    name: "أخيل عبدالحي روا",
    server: "https://server12.mp3quran.net/malaysia/akil/",
    readerId: 153,
    mushafId: 153,
  },
  {
    name: "أستاذ زامري",
    server: "https://server12.mp3quran.net/malaysia/zamri/",
    readerId: 154,
    mushafId: 154,
  },
  {
    name: "خالد المهنا",
    server: "https://server11.mp3quran.net/mohna/",
    readerId: 159,
    mushafId: 159,
  },
  {
    name: "عادل الكلباني",
    server: "https://server8.mp3quran.net/a_klb/",
    readerId: 160,
    mushafId: 160,
  },
  {
    name: "موسى بلال",
    server: "https://server11.mp3quran.net/bilal/",
    readerId: 161,
    mushafId: 161,
  },
  {
    name: "حسين آل الشيخ",
    server: "https://server11.mp3quran.net/alshaik/",
    readerId: 162,
    mushafId: 162,
  },
  {
    name: "حاتم فريد الواعر",
    server: "https://server11.mp3quran.net/hatem/",
    readerId: 163,
    mushafId: 163,
  },
  {
    name: "إبراهيم الجرمي",
    server: "https://server11.mp3quran.net/jormy/",
    readerId: 164,
    mushafId: 164,
  },
  {
    name: "محمود الرفاعي",
    server: "https://server11.mp3quran.net/mrifai/",
    readerId: 165,
    mushafId: 165,
  },
  {
    name: "ناصر العبيد",
    server: "https://server11.mp3quran.net/obaid/",
    readerId: 166,
    mushafId: 166,
  },
  {
    name: "واصل المذن",
    server: "https://server11.mp3quran.net/wasel/Rewayat-Hafs-A-n-Assem/",
    readerId: 167,
    mushafId: 167,
  },
  {
    name: "توفيق الصايغ",
    server: "https://server6.mp3quran.net/twfeeq/",
    readerId: 17,
    mushafId: 17,
  },
  {
    name: "إبراهيم الدوسري",
    server:
      "https://server10.mp3quran.net/ibrahim_dosri/Rewayat-Hafs-A-n-Assem/",
    readerId: 178,
    mushafId: 232,
  },
  {
    name: "جمال شاكر عبدالله",
    server: "https://server6.mp3quran.net/jamal/",
    readerId: 18,
    mushafId: 18,
  },
  {
    name: "جمعان العصيمي",
    server: "https://server6.mp3quran.net/jaman/",
    readerId: 181,
    mushafId: 181,
  },
  {
    name: "رضية عبدالرحمن",
    server: "https://server12.mp3quran.net/malaysia/rziah/",
    readerId: 183,
    mushafId: 183,
  },
  {
    name: "رقية سولونق",
    server: "https://server12.mp3quran.net/malaysia/rogiah/",
    readerId: 184,
    mushafId: 184,
  },
  {
    name: "سابينة مامات",
    server: "https://server12.mp3quran.net/malaysia/mamat/",
    readerId: 185,
    mushafId: 185,
  },
  {
    name: "سيدين عبدالرحمن",
    server: "https://server12.mp3quran.net/malaysia/sideen/",
    readerId: 187,
    mushafId: 187,
  },
  {
    name: "عبدالغني عبدالله",
    server: "https://server12.mp3quran.net/malaysia/abdulgani/",
    readerId: 188,
    mushafId: 188,
  },
  {
    name: "عبدالله فهمي",
    server: "https://server12.mp3quran.net/malaysia/fhmi/",
    readerId: 189,
    mushafId: 189,
  },
  {
    name: "حمد الدغريري",
    server: "https://server6.mp3quran.net/hamad/",
    readerId: 19,
    mushafId: 19,
  },
  {
    name: "محمد الحافظ",
    server: "https://server12.mp3quran.net/malaysia/hafz/",
    readerId: 190,
    mushafId: 190,
  },
  {
    name: "محمد حفص علي",
    server: "https://server12.mp3quran.net/malaysia/hfs/",
    readerId: 191,
    mushafId: 191,
  },
  {
    name: "محمد خير النور",
    server: "https://server12.mp3quran.net/malaysia/nor/",
    readerId: 192,
    mushafId: 192,
  },
  {
    name: "يوسف بن نوح أحمد",
    server: "https://server8.mp3quran.net/noah/",
    readerId: 193,
    mushafId: 193,
  },
  {
    name: "جمال الدين الزيلعي",
    server: "https://server11.mp3quran.net/zilaie/",
    readerId: 194,
    mushafId: 194,
  },
  {
    name: "معيض الحارثي",
    server: "https://server8.mp3quran.net/harthi/",
    readerId: 197,
    mushafId: 197,
  },
  {
    name: "محمد رشاد الشريف",
    server: "https://server10.mp3quran.net/rashad/",
    readerId: 198,
    mushafId: 198,
  },
  {
    name: "إبراهيم الجبرين",
    server: "https://server6.mp3quran.net/jbreen/",
    readerId: 2,
    mushafId: 2,
  },
  {
    name: "خالد الجليل",
    server: "https://server10.mp3quran.net/jleel/",
    readerId: 20,
    mushafId: 20,
  },
  {
    name: "أحمد الطرابلسي",
    server: "https://server10.mp3quran.net/trabulsi/",
    readerId: 201,
    mushafId: 201,
  },
  {
    name: "عبدالله الكندري",
    server: "https://server10.mp3quran.net/Abdullahk/",
    readerId: 202,
    mushafId: 202,
  },
  {
    name: "أحمد عامر",
    server: "https://server10.mp3quran.net/Aamer/",
    readerId: 203,
    mushafId: 203,
  },
  {
    name: "إبراهيم السعدان",
    server: "https://server10.mp3quran.net/IbrahemSadan/",
    readerId: 204,
    mushafId: 204,
  },
  {
    name: "أحمد الحذيفي",
    server: "https://server8.mp3quran.net/ahmad_huth/",
    readerId: 205,
    mushafId: 205,
  },
  {
    name: "محمد عثمان خان",
    server: "https://server6.mp3quran.net/khan/",
    readerId: 206,
    mushafId: 206,
  },
  {
    name: "يوسف الدغوش",
    server: "https://server7.mp3quran.net/dgsh/",
    readerId: 207,
    mushafId: 207,
  },
  {
    name: "وشيار حيدر اربيلي",
    server: "https://server11.mp3quran.net/wishear/",
    readerId: 209,
    mushafId: 209,
  },
  {
    name: "خالد القحطاني",
    server: "https://server10.mp3quran.net/qht/",
    readerId: 21,
    mushafId: 21,
  },
  {
    name: "عبدالله القرافي",
    server: "https://server16.mp3quran.net/a_alqrafi/Rewayat-Hafs-A-n-Assem/",
    readerId: 21136,
    mushafId: 10914,
  },
  {
    name: "عبدالبديع غيلان",
    server: "https://server16.mp3quran.net/A-Ghailan/Rewayat-Hafs-A-n-Assem/",
    readerId: 21148,
    mushafId: 10915,
  },
  {
    name: "محمد برهجي",
    server: "https://server16.mp3quran.net/M_Burhaji/Rewayat-Hafs-A-n-Assem/",
    readerId: 21181,
    mushafId: 340,
  },
  {
    name: "حسن الدغريري",
    server:
      "https://server16.mp3quran.net/H-Aldaghriri/Rewayat-Hafs-A-n-Assem/",
    readerId: 21183,
    mushafId: 10905,
  },
  {
    name: "محمد الفقيه",
    server: "https://server16.mp3quran.net/M_Alfaqih/Rewayat-Hafs-A-n-Assem/",
    readerId: 21184,
    mushafId: 10906,
  },
  {
    name: "جنيد آدم عبدالله",
    server: "https://server16.mp3quran.net/J-Abdullah/Rewayat-Hafs-A-n-Assem/",
    readerId: 21186,
    mushafId: 10908,
  },
  {
    name: "خالد الزيادي",
    server: "https://server16.mp3quran.net/K-Alzadi/Rewayat-Hafs-A-n-Assem/",
    readerId: 21187,
    mushafId: 10909,
  },
  {
    name: "الوليد الشمسان",
    server: "https://server14.mp3quran.net/shamsan/Rewayat-Hafs-A-n-Assem/",
    readerId: 21188,
    mushafId: 10910,
  },
  {
    name: "إبراهيم الشهري",
    server:
      "https://server16.mp3quran.net/Ibrahim-Al-Shahri/Rewayat-Hafs-A-n-Assem/",
    readerId: 21191,
    mushafId: 10911,
  },
  {
    name: "عبدالرحمن بن عبدالرزاق البدر",
    server: "https://server16.mp3quran.net/A-AlBadr/Rewayat-Hafs-A-n-Assem/",
    readerId: 21193,
    mushafId: 10913,
  },
  {
    name: "عليجان قوري حمدان",
    server: "https://server16.mp3quran.net/Alijon/Rewayat-Hafs-A-n-Assem/",
    readerId: 21196,
    mushafId: 10917,
  },
  {
    name: "عثمان الأنصاري",
    server: "https://server11.mp3quran.net/Othmn/",
    readerId: 216,
    mushafId: 216,
  },
  {
    name: "بندر بليله",
    server: "https://server6.mp3quran.net/balilah/",
    readerId: 217,
    mushafId: 217,
  },
  {
    name: "خالد الشريمي",
    server: "https://server12.mp3quran.net/shoraimy/",
    readerId: 218,
    mushafId: 218,
  },
  {
    name: "وديع اليمني",
    server: "https://server6.mp3quran.net/wdee3/",
    readerId: 219,
    mushafId: 219,
  },
  {
    name: "خالد عبدالكافي",
    server: "https://server11.mp3quran.net/kafi/",
    readerId: 22,
    mushafId: 22,
  },
  {
    name: "رعد محمد الكردي",
    server: "https://server6.mp3quran.net/kurdi/",
    readerId: 221,
    mushafId: 221,
  },
  {
    name: "عبدالرحمن العوسي",
    server: "https://server6.mp3quran.net/aloosi/",
    readerId: 225,
    mushafId: 225,
  },
  {
    name: "خالد الغامدي",
    server: "https://server6.mp3quran.net/ghamdi/",
    readerId: 226,
    mushafId: 226,
  },
  {
    name: "رمضان شكور",
    server: "https://server6.mp3quran.net/shakoor/",
    readerId: 227,
    mushafId: 227,
  },
  {
    name: "عبدالمجيد الأركاني",
    server: "https://server7.mp3quran.net/m_arkani/",
    readerId: 228,
    mushafId: 228,
  },
  {
    name: "محمد خليل القارئ",
    server: "https://server8.mp3quran.net/m_qari/",
    readerId: 229,
    mushafId: 229,
  },
  {
    name: "خالد الوهيبي",
    server: "https://server11.mp3quran.net/whabi/",
    readerId: 23,
    mushafId: 23,
  },
  {
    name: "رامي الدعيس",
    server: "https://server6.mp3quran.net/rami/",
    readerId: 230,
    mushafId: 230,
  },
  {
    name: "هزاع البلوشي",
    server: "https://server11.mp3quran.net/hazza/",
    readerId: 231,
    mushafId: 231,
  },
  {
    name: "عبدالرحمن الماجد",
    server: "https://server10.mp3quran.net/a_majed/",
    readerId: 236,
    mushafId: 236,
  },
  {
    name: "خليفة الطنيجي",
    server: "https://server12.mp3quran.net/tnjy/",
    readerId: 24,
    mushafId: 24,
  },
  {
    name: "سلمان العتيبي",
    server: "https://server11.mp3quran.net/salman/",
    readerId: 240,
    mushafId: 240,
  },
  {
    name: "محمد رفعت",
    server: "https://server14.mp3quran.net/refat/",
    readerId: 241,
    mushafId: 241,
  },
  {
    name: "عبدالله الموسى",
    server: "https://server14.mp3quran.net/mousa/Rewayat-Hafs-A-n-Assem/",
    readerId: 243,
    mushafId: 243,
  },
  {
    name: "عبدالله الخلف",
    server: "https://server14.mp3quran.net/khalf/",
    readerId: 244,
    mushafId: 244,
  },
  {
    name: "منصور السالمي",
    server: "https://server14.mp3quran.net/mansor/",
    readerId: 245,
    mushafId: 245,
  },
  {
    name: "صلاح مصلي",
    server: "https://server14.mp3quran.net/musali/",
    readerId: 246,
    mushafId: 246,
  },
  {
    name: "خالد الشارخ",
    server: "https://server14.mp3quran.net/sharekh/",
    readerId: 247,
    mushafId: 247,
  },
  {
    name: "ناصر العصفور",
    server: "https://server14.mp3quran.net/alosfor/",
    readerId: 248,
    mushafId: 248,
  },
  {
    name: "داود حمزة",
    server: "https://server9.mp3quran.net/hamza/",
    readerId: 25,
    mushafId: 25,
  },
  {
    name: "محمد البخيت",
    server: "https://server14.mp3quran.net/bukheet/",
    readerId: 250,
    mushafId: 250,
  },
  {
    name: "ناصر الماجد",
    server: "https://server14.mp3quran.net/nasser_almajed/",
    readerId: 251,
    mushafId: 251,
  },
  {
    name: "أحمد السويلم",
    server: "https://server14.mp3quran.net/swlim/Rewayat-Hafs-A-n-Assem/",
    readerId: 252,
    mushafId: 252,
  },
  {
    name: "إسلام صبحي",
    server: "https://server14.mp3quran.net/islam/Rewayat-Hafs-A-n-Assem/",
    readerId: 253,
    mushafId: 253,
  },
  {
    name: "بدر التركي",
    server: "https://server10.mp3quran.net/bader/Rewayat-Hafs-A-n-Assem/",
    readerId: 254,
    mushafId: 254,
  },
  {
    name: "هيثم الجدعاني",
    server: "https://server16.mp3quran.net/hitham/Rewayat-Hafs-A-n-Assem/",
    readerId: 255,
    mushafId: 255,
  },
  {
    name: "أحمد خليل شاهين",
    server: "https://server16.mp3quran.net/shaheen/Rewayat-Hafs-A-n-Assem/",
    readerId: 256,
    mushafId: 256,
  },
  {
    name: "سعد المقرن",
    server: "https://server16.mp3quran.net/saad/Rewayat-Hafs-A-n-Assem/",
    readerId: 257,
    mushafId: 257,
  },
  {
    name: "أحمد النفيس",
    server: "https://server16.mp3quran.net/nufais/Rewayat-Hafs-A-n-Assem/",
    readerId: 259,
    mushafId: 259,
  },
  {
    name: "عمر الدريويز",
    server: "https://server16.mp3quran.net/darweez/Rewayat-Hafs-A-n-Assem/",
    readerId: 260,
    mushafId: 260,
  },
  {
    name: "عبدالعزيز العسيري",
    server:
      "https://server16.mp3quran.net/abdulazizasiri/Rewayat-Hafs-A-n-Assem/",
    readerId: 263,
    mushafId: 263,
  },
  {
    name: "أحمد ديبان",
    server: "https://server16.mp3quran.net/deban/Rewayat-Hafs-A-n-Assem/",
    readerId: 265,
    mushafId: 265,
  },
  {
    name: "عبدالله كامل",
    server: "https://server16.mp3quran.net/kamel/Rewayat-Hafs-A-n-Assem/",
    readerId: 267,
    mushafId: 267,
  },
  {
    name: "بيشه وا قادر الكردي",
    server: "https://server16.mp3quran.net/peshawa/Rewayat-Hafs-A-n-Assem/",
    readerId: 268,
    mushafId: 268,
  },
  {
    name: "رشيد بلعالية",
    server: "https://server6.mp3quran.net/bl3/",
    readerId: 27,
    mushafId: 261,
  },
  {
    name: "نذير المالكي",
    server: "https://server16.mp3quran.net//nathier/Rewayat-Hafs-A-n-Assem/",
    readerId: 271,
    mushafId: 271,
  },
  {
    name: "محمود عبدالحكم",
    server:
      "https://server16.mp3quran.net/m_abdelhakam/Rewayat-Hafs-A-n-Assem/",
    readerId: 277,
    mushafId: 277,
  },
  {
    name: "أحمد عيسى المعصراوي",
    server:
      "https://server16.mp3quran.net/a_maasaraawi/Rewayat-Hafs-A-n-Assem/",
    readerId: 278,
    mushafId: 289,
  },
  {
    name: "زكريا حمامة",
    server: "https://server9.mp3quran.net/zakariya/",
    readerId: 28,
    mushafId: 28,
  },
  {
    name: "هاشم أبو دلال",
    server: "https://server16.mp3quran.net/h_abudalal/Rewayat-Hafs-A-n-Assem/",
    readerId: 280,
    mushafId: 292,
  },
  {
    name: "فؤاد الخامري",
    server: "https://server16.mp3quran.net/f_khamery/Rewayat-Hafs-A-n-Assem/",
    readerId: 281,
    mushafId: 293,
  },
  {
    name: "سيد أحمد هاشمي",
    server: "https://server16.mp3quran.net/s_hashemi/Rewayat-Hafs-A-n-Assem/",
    readerId: 282,
    mushafId: 294,
  },
  {
    name: "خالد كريم محمدي",
    server:
      "https://server16.mp3quran.net/kh_mohammadi/Rewayat-Hafs-A-n-Assem/",
    readerId: 283,
    mushafId: 295,
  },
  {
    name: "مال الله عبدالرحمن الجابر",
    server:
      "https://server16.mp3quran.net/mal-allah_jaber/Rewayat-Hafs-A-n-Assem/",
    readerId: 284,
    mushafId: 297,
  },
  {
    name: "سلمان الصديق",
    server: "https://server16.mp3quran.net/s_sadeiq/Rewayat-Hafs-A-n-Assem/",
    readerId: 285,
    mushafId: 298,
  },
  {
    name: "حسن صالح",
    server: "https://server16.mp3quran.net/h_saleh/Rewayat-Hafs-A-n-Assem/",
    readerId: 286,
    mushafId: 299,
  },
  {
    name: "عبدالرحمن الشحات",
    server: "https://server16.mp3quran.net/a_alshahhat/Rewayat-Hafs-A-n-Assem/",
    readerId: 287,
    mushafId: 302,
  },
  {
    name: "عيسى عمر سناكو",
    server: "https://server16.mp3quran.net/i_sanankoua/Rewayat-Hafs-A-n-Assem/",
    readerId: 288,
    mushafId: 303,
  },
  {
    name: "هارون بقائي",
    server: "https://server16.mp3quran.net/h_baqai/Rewayat-Hafs-A-n-Assem/",
    readerId: 289,
    mushafId: 304,
  },
  {
    name: "عبدالله بخاري",
    server: "https://server16.mp3quran.net/a_bukhari/Rewayat-Hafs-A-n-Assem/",
    readerId: 29,
    mushafId: 281,
  },
  {
    name: "صالح القريشي",
    server:
      "https://server16.mp3quran.net/s_alquraishi/Rewayat-Hafs-A-n-Assem/",
    readerId: 290,
    mushafId: 306,
  },
  {
    name: "إبراهيم العسيري",
    server: "https://server6.mp3quran.net/3siri/",
    readerId: 3,
    mushafId: 3,
  },
  {
    name: "سعد الغامدي",
    server: "https://server7.mp3quran.net/s_gmd/",
    readerId: 30,
    mushafId: 30,
  },
  {
    name: "صالح الشمراني",
    server: "https://server16.mp3quran.net/shamrani/Rewayat-Hafs-A-n-Assem/",
    readerId: 300,
    mushafId: 300,
  },
  {
    name: "فيصل الهاجري",
    server: "https://server16.mp3quran.net/f_hajry/Rewayat-Hafs-A-n-Assem/",
    readerId: 301,
    mushafId: 307,
  },
  {
    name: "أنس العمادي",
    server: "https://server16.mp3quran.net/a_alemadi/Rewayat-Hafs-A-n-Assem/",
    readerId: 302,
    mushafId: 314,
  },
  {
    name: "عبدالملك العسكر",
    server: "https://server16.mp3quran.net/a_alaskar/Rewayat-Hafs-A-n-Assem/",
    readerId: 303,
    mushafId: 315,
  },
  {
    name: "عبدالكريم الحازمي",
    server: "https://server16.mp3quran.net/a_alhazmi/Rewayat-Hafs-A-n-Assem/",
    readerId: 304,
    mushafId: 316,
  },
  {
    name: "عبدالله المشعل",
    server: "https://server16.mp3quran.net/a-almishal/Rewayat-Hafs-A-n-Assem/",
    readerId: 306,
    mushafId: 318,
  },
  {
    name: "سعود الشريم",
    server: "https://server7.mp3quran.net/shur/",
    readerId: 31,
    mushafId: 31,
  },
  {
    name: "سهل ياسين",
    server: "https://server6.mp3quran.net/shl/",
    readerId: 32,
    mushafId: 32,
  },
  {
    name: "زكي داغستاني",
    server: "https://server9.mp3quran.net/zaki/",
    readerId: 33,
    mushafId: 33,
  },
  {
    name: "سامي الحسن",
    server: "https://server8.mp3quran.net/sami_hsn/",
    readerId: 34,
    mushafId: 34,
  },
  {
    name: "سامي الدوسري",
    server: "https://server8.mp3quran.net/sami_dosr/",
    readerId: 35,
    mushafId: 35,
  },
  {
    name: "سيد رمضان",
    server: "https://server12.mp3quran.net/sayed/",
    readerId: 36,
    mushafId: 36,
  },
  {
    name: "شعبان الصياد",
    server: "https://server11.mp3quran.net/shaban/",
    readerId: 37,
    mushafId: 37,
  },
  {
    name: "شيرزاد عبدالرحمن طاهر",
    server: "https://server12.mp3quran.net/taher/",
    readerId: 38,
    mushafId: 38,
  },
  {
    name: "صابر عبدالحكم",
    server: "https://server12.mp3quran.net/hkm/",
    readerId: 39,
    mushafId: 39,
  },
  {
    name: "شيخ أبو بكر الشاطري",
    server: "https://server11.mp3quran.net/shatri/",
    readerId: 4,
    mushafId: 4,
  },
  {
    name: "صالح الصاهود",
    server: "https://server8.mp3quran.net/sahood/",
    readerId: 40,
    mushafId: 40,
  },
  {
    name: "صالح آل طالب",
    server: "https://server9.mp3quran.net/tlb/",
    readerId: 41,
    mushafId: 41,
  },
  {
    name: "صالح الهبدان",
    server: "https://server6.mp3quran.net/habdan/",
    readerId: 42,
    mushafId: 42,
  },
  {
    name: "صلاح البدير",
    server: "https://server6.mp3quran.net/s_bud/",
    readerId: 43,
    mushafId: 43,
  },
  {
    name: "صلاح الهاشم",
    server: "https://server12.mp3quran.net/salah_hashim_m/",
    readerId: 44,
    mushafId: 44,
  },
  {
    name: "صلاح بو خاطر",
    server: "https://server8.mp3quran.net/bu_khtr/",
    readerId: 46,
    mushafId: 46,
  },
  {
    name: "مختار الحاج",
    server: "https://server16.mp3quran.net/mukhtar_haj/Rewayat-Hafs-A-n-Assem/",
    readerId: 47,
    mushafId: 283,
  },
  {
    name: "عادل ريان",
    server: "https://server8.mp3quran.net/ryan/",
    readerId: 48,
    mushafId: 48,
  },
  {
    name: "عبدالبارئ الثبيتي",
    server: "https://server6.mp3quran.net/thubti/",
    readerId: 49,
    mushafId: 49,
  },
  {
    name: "أحمد بن علي العجمي",
    server: "https://server10.mp3quran.net/ajm/",
    readerId: 5,
    mushafId: 5,
  },
  {
    name: "عبدالبارئ محمد",
    server: "https://server12.mp3quran.net/bari/",
    readerId: 50,
    mushafId: 50,
  },
  {
    name: "عبدالباسط عبدالصمد",
    server: "https://server7.mp3quran.net/basit/",
    readerId: 51,
    mushafId: 53,
  },
  {
    name: "عبدالرحمن السديس",
    server: "https://server11.mp3quran.net/sds/",
    readerId: 54,
    mushafId: 54,
  },
  {
    name: "عبدالعزيز الأحمد",
    server: "https://server11.mp3quran.net/a_ahmed/",
    readerId: 55,
    mushafId: 55,
  },
  {
    name: "عبدالعزيز الزهراني",
    server: "https://server9.mp3quran.net/zahrani/",
    readerId: 56,
    mushafId: 56,
  },
  {
    name: "عبدالله البريمي",
    server: "https://server8.mp3quran.net/brmi/",
    readerId: 57,
    mushafId: 57,
  },
  {
    name: "عبدالله البعيجان",
    server: "https://server8.mp3quran.net/buajan/",
    readerId: 58,
    mushafId: 58,
  },
  {
    name: "عبدالله المطرود",
    server: "https://server8.mp3quran.net/mtrod/",
    readerId: 59,
    mushafId: 59,
  },
  {
    name: "أحمد الحواشي",
    server: "https://server11.mp3quran.net/hawashi/",
    readerId: 6,
    mushafId: 6,
  },
  {
    name: "عبدالله بصفر",
    server: "https://server6.mp3quran.net/bsfr/",
    readerId: 60,
    mushafId: 60,
  },
  {
    name: "عبدالله خياط",
    server: "https://server12.mp3quran.net/kyat/",
    readerId: 61,
    mushafId: 61,
  },
  {
    name: "عبدالله عواد الجهني",
    server: "https://server13.mp3quran.net/jhn/",
    readerId: 62,
    mushafId: 62,
  },
  {
    name: "عبدالله غيلان",
    server: "https://server8.mp3quran.net/gulan/",
    readerId: 63,
    mushafId: 63,
  },
  {
    name: "عبدالرشيد صوفي",
    server: "https://server16.mp3quran.net/soufi/Rewayat-Hafs-A-n-Assem/",
    readerId: 64,
    mushafId: 258,
  },
  {
    name: "عبدالمحسن الحارثي",
    server: "https://server6.mp3quran.net/mohsin_harthi/",
    readerId: 66,
    mushafId: 66,
  },
  {
    name: "عبدالمحسن القاسم",
    server: "https://server8.mp3quran.net/qasm/",
    readerId: 67,
    mushafId: 67,
  },
  {
    name: "عبدالمحسن العسكر",
    server: "https://server6.mp3quran.net/askr/",
    readerId: 68,
    mushafId: 68,
  },
  {
    name: "عبدالمحسن العبيكان",
    server: "https://server12.mp3quran.net/obk/",
    readerId: 69,
    mushafId: 69,
  },
  {
    name: "أحمد سعود",
    server: "https://server11.mp3quran.net/saud/",
    readerId: 7,
    mushafId: 7,
  },
  {
    name: "عبدالهادي أحمد كناكري",
    server: "https://server6.mp3quran.net/kanakeri/",
    readerId: 70,
    mushafId: 70,
  },
  {
    name: "عبدالودود حنيف",
    server: "https://server8.mp3quran.net/wdod/",
    readerId: 71,
    mushafId: 71,
  },
  {
    name: "عبدالولي الأركاني",
    server: "https://server6.mp3quran.net/arkani/",
    readerId: 72,
    mushafId: 72,
  },
  {
    name: "علي أبو هاشم",
    server: "https://server9.mp3quran.net/abo_hashim/",
    readerId: 73,
    mushafId: 73,
  },
  {
    name: "علي بن عبدالرحمن الحذيفي",
    server: "https://server9.mp3quran.net/hthfi/",
    readerId: 74,
    mushafId: 74,
  },
  {
    name: "علي جابر",
    server: "https://server11.mp3quran.net/a_jbr/",
    readerId: 76,
    mushafId: 76,
  },
  {
    name: "علي حجاج السويسي",
    server: "https://server9.mp3quran.net/hajjaj/",
    readerId: 77,
    mushafId: 77,
  },
  {
    name: "عماد زهير حافظ",
    server: "https://server6.mp3quran.net/hafz/",
    readerId: 78,
    mushafId: 78,
  },
  {
    name: "عبدالعزيز التركي",
    server: "https://server16.mp3quran.net/a_turki/Rewayat-Hafs-A-n-Assem/",
    readerId: 79,
    mushafId: 282,
  },
  {
    name: "أحمد صابر",
    server: "https://server8.mp3quran.net/saber/",
    readerId: 8,
    mushafId: 8,
  },
  {
    name: "فارس عباد",
    server: "https://server8.mp3quran.net/frs_a/",
    readerId: 81,
    mushafId: 81,
  },
  {
    name: "فهد العتيبي",
    server: "https://server8.mp3quran.net/fahad_otibi/",
    readerId: 82,
    mushafId: 82,
  },
  {
    name: "فهد الكندري",
    server: "https://server11.mp3quran.net/kndri/",
    readerId: 83,
    mushafId: 83,
  },
  {
    name: "فواز الكعبي",
    server: "https://server8.mp3quran.net/fawaz/",
    readerId: 84,
    mushafId: 84,
  },
  {
    name: "لافي العوني",
    server: "https://server6.mp3quran.net/lafi/",
    readerId: 85,
    mushafId: 85,
  },
  {
    name: "ناصر القطامي",
    server: "https://server6.mp3quran.net/qtm/",
    readerId: 86,
    mushafId: 86,
  },
  {
    name: "نبيل الرفاعي",
    server: "https://server9.mp3quran.net/nabil/",
    readerId: 87,
    mushafId: 87,
  },
  {
    name: "نعمة الحسان",
    server: "https://server8.mp3quran.net/namh/",
    readerId: 88,
    mushafId: 88,
  },
  {
    name: "هاني الرفاعي",
    server: "https://server8.mp3quran.net/hani/",
    readerId: 89,
    mushafId: 89,
  },
  {
    name: "أحمد نعينع",
    server: "https://server11.mp3quran.net/ahmad_nu/",
    readerId: 9,
    mushafId: 9,
  },
  {
    name: "وليد الدليمي",
    server: "https://server8.mp3quran.net/dlami/",
    readerId: 90,
    mushafId: 90,
  },
  {
    name: "ياسر الدوسري",
    server: "https://server11.mp3quran.net/yasser/",
    readerId: 92,
    mushafId: 92,
  },
  {
    name: "ياسر القرشي",
    server: "https://server9.mp3quran.net/qurashi/",
    readerId: 93,
    mushafId: 93,
  },
  {
    name: "ياسر الفيلكاوي",
    server: "https://server6.mp3quran.net/fyl/",
    readerId: 94,
    mushafId: 94,
  },
  {
    name: "يحيى حوا",
    server: "https://server12.mp3quran.net/yahya/",
    readerId: 96,
    mushafId: 96,
  },
  {
    name: "يوسف الشويعي",
    server: "https://server9.mp3quran.net/yousef/",
    readerId: 97,
    mushafId: 97,
  },
  {
    name: "عبدالله عبدل",
    server: "https://server16.mp3quran.net/a_abdl/Rewayat-Hafs-A-n-Assem/",
    readerId: 98,
    mushafId: 284,
  },
] as const